name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html selenium

    - name: Run Selenium tests on Chrome
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        pytest -v --html=results/report_${{ matrix.python-version }}.html shopping.py
      continue-on-error: true # Continue even if the test step fails to capture and upload the report

    - name: Upload test results for ${{ matrix.python-version }}
      if: always() # Ensure this runs even if the previous step fails
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ matrix.python-version }}
        path: results/report_${{ matrix.python-version }}.html

